
#include <iostream>
#include <string>
#include <fstream>
#include<sstream>
#include <ctime>
#include <cstdlib>
#include "Account.h"
#include <string>
#include "LinkedList.h"
using namespace std;

class StockAccount:public Account{
    LinkedList list; // 
    int result_index; // This is either 1 or 2 randomly generated by rand(), to select result_1.txt or result_2.txt
    public:

    StockAccount();
    ~StockAccount();

    void load_portfolio();
    void update_portfolio();
    void update_total();
    bool check_stock(string stock);
    void buy(string stock,int shares,string sort_type);
    void sell(string stock,int shares);
    void record_transaction(string type,string stock, int share, float price);
    float getValue(string str);
    void displayStock(string str);
    void split(string str,string arr[10]);
    void display_transaction();
    void display_portfolio();
    void show_all_stock();

};

